CREATE TABLE ROLES (
    ROLE VARCHAR(1000),
    CONSTRAINT ROLES_PK PRIMARY KEY (ROLE)
);

CREATE TABLE COUNTRIES(
  COUNTRY VARCHAR(50),
  COUNTRY_CODE VARCHAR(8) UNIQUE NOT NULL,
  CONSTRAINT COUNTRIES_PK PRIMARY KEY (COUNTRY)
);

CREATE TABLE USERS (
    ID INT GENERATED ALWAYS AS IDENTITY,
    FIRST_NAME VARCHAR(1000) NOT NULL,
    LAST_NAME VARCHAR(1000) NOT NULL,
    EMAIL TEXT UNIQUE NOT NULL,
    ROLE VARCHAR(1000) NOT NULL , -- FK
    CONTACT_NO VARCHAR(11) NOT NULL UNIQUE,
    EMERGENCY_CONTACT_NO VARCHAR(11) NOT NULL  UNIQUE,
    BIRTH_DATE DATE NOT NULL ,
    PERMANENT_ADDRESS TEXT NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL, -- FK
    PASSPORT_ID VARCHAR(15) NOT NULL UNIQUE,


    CONSTRAINT USERS_PK PRIMARY KEY (ID),
    CONSTRAINT EMAIL_FORMAT_CHECK
    CHECK (EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT USERS_CONTACT_NO_CHECK
    CHECK (CONTACT_NO ~ '^\+?\d{10,15}$'),
    CONSTRAINT USERS_EMERGENCY_CONTACT_NO CHECK ( EMERGENCY_CONTACT_NO ~ '^\+?\d{10,15}$' ),
    CONSTRAINT USERS_ROLE_FK
    FOREIGN KEY (ROLE)
    REFERENCES ROLES(ROLE),
    CONSTRAINT USERS_COUNTRY_FK FOREIGN KEY(COUNTRY) REFERENCES COUNTRIES(COUNTRY)
);

CREATE TABLE ROOM_TYPES(
    ROOM_TYPE VARCHAR(15),
    CONSTRAINT ROOM_TYPES_PK PRIMARY KEY (ROOM_TYPE)
);


CREATE TABLE FLOORS(
    FLOOR_NO INT,
    CONSTRAINT FLOORS_PK PRIMARY KEY (FLOOR_NO)
);

CREATE TABLE ROOMS(
    ID INT GENERATED ALWAYS AS IDENTITY,
    ROOM_TYPE VARCHAR(15) NOT NULL,
    FLOOR_NO INT NOT NULL,
    PER_DAY_RENT_FEE FLOAT,
    CONSTRAINT ROOMS_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_ROOMS_TYPES_FK FOREIGN KEY (ROOM_TYPE) REFERENCES ROOM_TYPES(ROOM_TYPE) ,
    CONSTRAINT USERS_FLOOR_NO_FK FOREIGN KEY (FLOOR_NO) REFERENCES FLOORS(FLOOR_NO)
);


CREATE TABLE ROOM_RENT_INFORMATION(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT NOT NULL ,
    ROOM_ID INT NOT NULL ,
    ROOM_RENT_DAYS INT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    MEAL_STATUS BOOLEAN DEFAULT(TRUE),
    TOTAL_MEAL_COUNT INT DEFAULT(90),
    CONSTRAINT ROOM_RENT_INFORMATION_USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT ROOM_RENT_INFORMATION_ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ID)
);

CREATE TYPE TRANSACTION_TYPE AS ENUM ('DEBIT', 'CREDIT');
CREATE TYPE PAYMENT_METHOD  AS ENUM ('BKASH', 'NAGAD','ROCKET','ONLINE','OFFLINE');

CREATE TABLE TRANSACTIONS(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT, --FK
    ROOM_NO INT, --FK
    PAYMENT_DATE DATE NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    TOTAL_AMOUNT FLOAT,
    PAID_AMOUNT FLOAT,
    PAYMENT_METHOD PAYMENT_METHOD NOT NULL,
    TRANSACTION_TYPE TRANSACTION_TYPE NOT NULL,
    CONSTRAINT TRANSACTIONS_PK PRIMARY KEY (ID),
    CONSTRAINT TRANSACTIONS_FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT TRANSACTIONS_FK_ROOM_NO FOREIGN KEY (ROOM_NO) REFERENCES ROOMS(ID)
);


CREATE TABLE COMPLAINT_STATUS(
    STATUS VARCHAR(20),
    CONSTRAINT COMPLAINT_STATUS_PK PRIMARY KEY (STATUS)
);


CREATE TABLE COMPLAINT(
    ID INT GENERATED ALWAYS AS IDENTITY,
    USER_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    DESCRIPTION TEXT,
    COMPLAINT_STATUS VARCHAR(20) NOT NULL,
    COMPLAINT_DATE TIMESTAMP DEFAULT now(),
    CONSTRAINT COMPLAINTS_PK PRIMARY KEY (ID),
    CONSTRAINT COMPLAINTS_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT COMPLAINT_ROOM_ID_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOMS(ID)
);

CREATE TABLE REVIEWS(
    ID INT GENERATED ALWAYS AS  IDENTITY,
    USER_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    DESCRIPTION TEXT,
    REVIEW_DATE TIMESTAMP DEFAULT now(),
    CONSTRAINT REVIEW_PK PRIMARY KEY (ID),
    CONSTRAINT REVIEW_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT REVIEW_ROOM_ID_FK FOREIGN KEY(ROOM_ID) REFERENCES ROOMS(ID)
);
